# Generated by Django 4.2.1 on 2023-06-12 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('prenom', models.CharField(max_length=128)),
                ('mail', models.EmailField(max_length=128)),
                ('role', models.CharField(max_length=128)),
                ('entreprise', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('type_privé', models.BooleanField()),
                ('commentaire', models.CharField(max_length=244)),
            ],
        ),
    ]
