# Generated by Django 4.2.1 on 2023-09-20 19:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [('contactsApp', '0001_initial'), ('contactsApp', '0002_entite'), ('contactsApp', '0003_user'), ('contactsApp', '0004_remove_contact_entreprise_contact_entite'), ('contactsApp', '0005_profil'), ('contactsApp', '0006_alter_profil_user_delete_user'), ('contactsApp', '0007_rename_profil_userprofile'), ('contactsApp', '0008_userprofile_birth_date_userprofile_first_name_and_more'), ('contactsApp', '0009_remove_userprofile_first_name_and_more'), ('contactsApp', '0010_remove_contact_commentaire_remove_contact_type_privé'), ('contactsApp', '0011_contact_commentaire_contact_type_prive'), ('contactsApp', '0012_contact_source_acquisition'), ('contactsApp', '0013_alter_contact_source_acquisition'), ('contactsApp', '0014_user_alter_userprofile_user'), ('contactsApp', '0015_alter_userprofile_user_delete_user'), ('contactsApp', '0016_userprofile_first_name_userprofile_last_name'), ('contactsApp', '0017_remove_userprofile_first_name_and_more')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('numero', models.IntegerField()),
                ('adresse', models.CharField(max_length=128)),
                ('code_postal', models.IntegerField()),
                ('ville', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('prenom', models.CharField(max_length=128)),
                ('mail', models.EmailField(max_length=128)),
                ('role', models.CharField(max_length=128)),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('entite', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to='contactsApp.entite')),
                ('commentaire', models.CharField(max_length=244, null=True)),
                ('type_prive', models.BooleanField(null=True)),
                ('source_acquisition', models.CharField(choices=[('Linkedin', 'Linkedin'), ('Reco', 'Recommandation'), ('RDV tel', 'RDV télephonique')], max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to='images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField(null=True)),
            ],
        ),
    ]
