# Generated by Django 4.2.1 on 2023-06-12 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=128)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='images')),
                ('numero', models.IntegerField()),
                ('adresse', models.CharField(max_length=128)),
                ('code_postal', models.IntegerField()),
                ('ville', models.CharField(max_length=128)),
            ],
        ),
    ]
