# Generated by Django 4.2.1 on 2023-08-17 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsApp', '0002_entite'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=64)),
                ('password', models.CharField(max_length=64)),
                ('email', models.EmailField(max_length=64)),
            ],
        ),
    ]
