# Generated by Django 4.2.1 on 2023-08-17 15:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactsApp', '0003_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='entreprise',
        ),
        migrations.AddField(
            model_name='contact',
            name='entite',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to='contactsApp.entite'),
        ),
    ]
