# Generated by Django 4.2.1 on 2023-08-21 18:31

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contactsApp', '0006_alter_profil_user_delete_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profil',
            new_name='UserProfile',
        ),
    ]
