# Generated by Django 4.2.1 on 2023-08-28 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactsApp', '0008_userprofile_birth_date_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
