# Generated by Django 4.2.1 on 2023-08-28 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactsApp', '0009_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='commentaire',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='type_privé',
        ),
    ]
