# Generated by Django 4.2.1 on 2023-08-28 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsApp', '0010_remove_contact_commentaire_remove_contact_type_privé'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='commentaire',
            field=models.CharField(max_length=244, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='type_prive',
            field=models.BooleanField(null=True),
        ),
    ]
