# Generated by Django 4.2.1 on 2023-08-28 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsApp', '0011_contact_commentaire_contact_type_prive'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='source_acquisition',
            field=models.CharField(choices=[(1, 'Linkedin'), (2, 'Recommandation'), (3, 'RDV télephonique')], max_length=128, null=True),
        ),
    ]
