# Generated by Django 4.2.1 on 2023-08-28 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsApp', '0012_contact_source_acquisition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='source_acquisition',
            field=models.CharField(choices=[('Linkedin', 'Linkedin'), ('Reco', 'Recommandation'), ('RDV tel', 'RDV télephonique')], max_length=128, null=True),
        ),
    ]
