# Generated by Django 4.2.1 on 2023-09-18 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactsApp', '0016_userprofile_first_name_userprofile_last_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='last_name',
        ),
    ]
