# Generated by Django 4.2.1 on 2023-09-22 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contactsApp', '0001_squashed_0017_remove_userprofile_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceAcquisition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_acquisition', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='contact',
            name='source_acquisition',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact', to='contactsApp.sourceacquisition'),
        ),
    ]
