# Generated by Django 4.2.1 on 2023-09-22 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactsApp', '0019_remove_userprofile_image_userprofile_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='email',
            field=models.EmailField(max_length=64, null=True, unique=True),
        ),
    ]
